#pragma once
// Shared by the three build programs: set up the paths and the common
// generators, so each member's build.mcpp is only the list of what IT needs.
//
// ⚠️ The FOUR shared outputs — config.h, glibconfig.h, glib/gversionmacros.h,
// glib/glib-visibility.h — are produced by every member into its OWN include/.
// glib's headers are what everything includes, so every member needs them; and
// a member that generates what it compiles cannot be caught by the failure
// described at the top of generators.h.
inline void mcpp_glib_common_setup()
{
    namespace fs = std::filesystem;
    g_root = fs::path(mcpp::manifest_dir());
    g_up   = (g_root / ".." / ".." / "upstream").lexically_normal();
    g_inc  = (g_root / "include").lexically_normal();

    std::error_code ec;
    // Wiped so a header that stopped being generated stops shadowing too. The
    // DIRECTORY survives with its .gitkeep, because mcpp reads `include_dirs`
    // before running this program and silently drops an entry that is not there.
    for (const char *sub : {"glib", "gobject", "gmodule"})
        fs::remove_all(g_inc / sub, ec);
    for (const char *f : {"config.h", "glibconfig.h", "gmoduleconf.h"})
        fs::remove(g_inc / f, ec);
    fs::create_directories(g_inc, ec);

    gen_version_macros();
    gen_visibility("GLIB", g_inc / "glib" / "glib-visibility.h");
    gen_glibconfig();
    gen_config();
}

// ── meson configure_file → gio/gnetworking.h ────────────────────────────────
//
// One substitution, and on Linux it is empty: NAMESER_COMPAT_INCLUDE names
// <arpa/nameser_compat.h> on the platforms whose <arpa/nameser.h> does not
// already define the DNS constants. glibc's does.
inline void gen_gnetworking()
{
    namespace fs = std::filesystem;
    const fs::path in = g_up / "gio" / "gnetworking.h.in";
    std::string body = slurp(in);
    const std::string k = "@NAMESER_COMPAT_INCLUDE@";
    for (std::size_t p = body.find(k); p != std::string::npos; p = body.find(k))
        body.replace(p, k.size(), "");
    std::error_code ec;
    fs::create_directories(g_inc / "gio", ec);
    std::ofstream(g_inc / "gio" / "gnetworking.h")
        << "/* GENERATED by build.mcpp from upstream/gio/gnetworking.h.in. */\n"
        << body;
    mcpp::rerun_if_changed(in.string().c_str());
}

// ── gobject/glib-mkenums, over gio's public headers ─────────────────────────
//
// The same generator as glib's, pointed at many headers instead of one. What
// changes at this scale is not the loop but the ANNOTATIONS: gio uses
// `/*< flags >*/`, `/*< nick=… >*/` and `/*< prefix=… >*/`, and 144 GTK-DOC
// `/*< private >*/` that mean nothing here.
//
// ⚠️ The header set is upstream's INSTALLED headers, not `gio/*.h`. The private
// ones (gioprivate.h, gdbusprivate.h…) also contain enums, and registering
// those as GTypes would put names in gio's ABI that upstream does not have.
inline void gen_gio_enumtypes()
{
    namespace fs = std::filesystem;
    const fs::path gio = g_up / "gio";

    // Upstream installs gio.h and everything it includes. Deriving the set by
    // scanning gio.h's includes keeps it in step with a version bump, which a
    // transcribed list would not.
    std::vector<fs::path> headers;
    {
        std::ifstream h(gio / "gio.h");
        std::string l;
        while (std::getline(h, l)) {
            const std::size_t a = l.find("<gio/");
            if (a == std::string::npos) continue;
            const std::size_t b = l.find('>', a);
            if (b == std::string::npos) continue;
            const std::string n = l.substr(a + 5, b - a - 5);
            if (n.size() > 2 && n.compare(n.size() - 2, 2, ".h") == 0
                && fs::exists(gio / n))
                headers.push_back(gio / n);
        }
    }
    // gnetworking.h is passed to mkenums by upstream as a separate argument;
    // it is generated, so it comes from the output tree.
    if (fs::exists(g_inc / "gio" / "gnetworking.h"))
        headers.push_back(g_inc / "gio" / "gnetworking.h");

    if (headers.size() < 40) {
        note("gio.h yielded only %zu installed headers; the enum scan would be\n"
             "silently incomplete and gio would be missing GTypes its own\n"
             "headers declare.\n", headers.size());
        std::exit(1);
    }

    std::vector<std::pair<std::string, std::vector<enum_def>>> per_file;
    std::size_t total = 0;
    for (const auto &h : headers) {
        auto e = scan_enums(h);
        mcpp::rerun_if_changed(h.string().c_str());
        if (e.empty()) continue;
        total += e.size();
        per_file.emplace_back(h.filename().string(), std::move(e));
    }
    if (total < 70) {
        note("only %zu enums found across gio's headers; upstream registers 82, and a\n"
             "short count means the scanner stopped understanding something.\n",
             total);
        std::exit(1);
    }

    write_enumtypes(gio / "gioenumtypes.h.template", g_inc / "gio" / "gioenumtypes.h",
                    per_file);
    write_enumtypes(gio / "gioenumtypes.c.template", g_inc / "gio" / "gioenumtypes.c",
                    per_file);
    note("gioenumtypes: %zu enums across %zu headers\n", total, per_file.size());
}

// ⚠️ gio INCLUDES ITS GENERATED HEADERS BOTH WAYS, and both have to work.
// Measured across gio's sources:
//
//     "gioenumtypes.h"        48    <gio/gioenumtypes.h>    3
//     "gnetworking.h"          9    <gio/gnetworking.h>     2
//
// The real file lives under `gio/` so the angle-bracket form resolves through
// `include/`; a one-line forwarder at the top level answers the bare name.
// Forwarding rather than writing twice keeps one source of truth — and the
// nested directory needs no `include_dirs` entry of its own, which matters
// because an entry naming a directory that does not exist yet is silently
// dropped.
inline void gen_flat_forwarders()
{
    namespace fs = std::filesystem;
    for (const char *n : {"gioenumtypes.h", "gnetworking.h"}) {
        std::ofstream(g_inc / n)
            << "/* GENERATED by build.mcpp.\n"
               " *\n"
               " * gio includes this both as \"" << n << "\" and as\n"
               " * <gio/" << n << ">. The real file is the nested one; this\n"
               " * answers the bare spelling. */\n"
            << "#include <gio/" << n << ">\n";
    }
}
